Add per-admin parameter to Panorama push
PaloAltoNetworks/pan-os-ansible pull request #366
Opened 2022-12-22 13:47 UTC by jamesholland-uk

## Description
Adding support for the [PAN-OS 10.2 feature](https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-release-notes/features-introduced-in-pan-os/panorama-features) of Administrator-Level Push from Panorama to Managed Devices

Depends upon [supporting change in pan-os-python](https://github.com/PaloAltoNetworks/pan-os-python/pull/485).

## Motivation and Context
Motivation is adding support for a new PAN-OS feature, and also to support adding this feature in pan-os-ansible ([ref - will close this issue](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/361))

## How Has This Been Tested?
Tested locally, with Panorama 11.0.0 and managed firewall 10.2.3
```
  tasks:
    - name: Commit and Push template configuration
      panos_commit_push:
        provider: "{{ device }}"
        style: "device group"
        name: "poc-dg"
        admins:
          - "other"
        include_template: no
        force_template_values: no
      register: results
    - debug:
        msg: "Job ID: {{ results.jobid }} finished"
```

## Screenshots (if appropriate)
![Screenshot 2022-12-22 at 13 44 56](https://user-images.githubusercontent.com/6574404/209147633-fd1d1125-4783-4399-a022-5ad8bdaadee0.png)

## Types of changes
- New feature (non-breaking change which adds functionality)

## Checklist
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

2023-01-11 09:21 UTC, shinmog requested changes
This change requires a certain minimum version of PAN-OS, which is present in the docstring, so that's good.

However, it also requires a certain minimum version of pan-os-python, which is not reflected in the code right now.  You can configure this as `min_pandevice_version`.  However, you can't actually do that until you know which version of pan-os-python is going to contain the change for admin specific push.  So pan-os-python needs to release that first, then this code can reflect that.

2023-01-11 09:29 UTC, jamesholland-uk commented
Thanks @shinmog, that all makes sense. The change in pan-os-python is merged and awaiting release. It didn't pass all the tests, but that was the issue in CI with the version of the poetry action (and also poetry itself got a version upgrade), and that change is also merged. So do we 1) push the pan-os-python CI change from develop to master, 2) rerun the CI tests on my PR in pan-os-python, 3) push the changes from the PR from develop to master, 4) get the pan-os-python version and put it into this PR per your note, 5) release pan-os-ansible? Phew!

2023-01-13 18:48 UTC, jamesholland-uk commented
1) push the pan-os-python CI change from develop to master - done
2) rerun the CI tests on my PR in pan-os-python - done
3) push the changes from the PR from develop to master - done
4) get the pan-os-python version and put it into this PR per your note - done
5) release pan-os-ansible...........

Let me know if there are any other modifications needed for us to go live with this PR?

2023-01-16 21:46 UTC, shinmog approved these changes
lgtm

2023-01-17 10:06 UTC, merged